export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_LOGIN_USER_FAILURE = 'AUTH_LOGIN_USER_FAILURE';
export const AUTH_LOGIN_USER_EXPIRED = 'AUTH_LOGIN_USER_EXPIRED';
export const AUTH_LOGIN_CLEAN_ERRORS = 'AUTH_LOGIN_CLEAN_ERRORS';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_SAVE_USERS_INFORMATION = 'AUTH_SAVE_USERS_INFORMATION';
export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const SUBMIT_SIGNUP_FORM_SAVE = 'SUBMIT_SIGNUP_FORM_SAVE';
export const SUBMIT_LOGIN_FORM_SAVE = 'SUBMIT_LOGIN_FORM_SAVE';

export const LOADING_MODAL_OPEN = 'LOADING_MODAL_OPEN';
export const LOADING_MODAL_CLOSE = 'LOADING_MODAL_CLOSE';
export const WARNING_MODAL_OPEN = 'WARNING_MODAL_OPEN';
export const WARNING_MODAL_CLOSE = 'WARNING_MODAL_CLOSE';

export const SUBMIT_ORDER_DEVICE_FORM_REQUEST = 'SUBMIT_ORDER_DEVICE_FORM_REQUEST';
export const SUBMIT_ORDER_DEVICE_FORM_SAVE = 'SUBMIT_ORDER_DEVICE_FORM_SAVE';
export const SUBMIT_ORDER_DEVICE_FORM_SUCCESS = 'SUBMIT_ORDER_DEVICE_FORM_SUCCESS';
export const SUBMIT_ORDER_DEVICE_FORM_FAILURE = 'SUBMIT_ORDER_DEVICE_FORM_FAILURE';

export const BUYDEVICE_MODAL_CLOSE = 'BUYDEVICE_MODAL_CLOSE';
export const BUYDEVICE_MODAL_OPEN = 'BUYDEVICE_MODAL_OPEN';
